python main_pretrain.py \
    --alpha_entropy 0 \
    --alpha_sparsity 0.75 \
    --batch_size 128 \
    --dataset he \
    --temperature 0.2 \
    --lr 0.18955780763100336 \
    --mask_lr 0.4987622134866454 \
    --optimizer sgd \
    --scheduler warmup_cosine \
    --weight_decay 0.0001 \
    --max_epochs 400 \
    --brightness 0.7 \
    --contrast 0.6 \
    --hue 0.15 \
    --saturation 0.8 \
    --N 4 \
    --encoder resnet18 \
    --mask_fbase 8 \
    --auto_mask \
    --method simclr_adios_s \
    --output_dim 128 \
    --proj_hidden_dim 2048 \
    --unet_norm gn \
    --gpus '0, 1, 2, 3' \
    --validation_frequency 0 \
    --data_dir /data/pwojcik/images_he_seg1000/ \
    --wandb_dir /data/pwojcik/adios_wandb \
    --checkpoint_dir /data/pwojcik/adios/checkpoints \
    --project adios \
    --entity piotrmwojcik \
    --name simclr_adios_s_resnet18_imagenet100 \
    --wandb True
# note: replace --data_dir, --wandb_dir, --checkpoint_dir, --project, --entity, --name with your custom values.
